#ifdef __cplusplus
extern "C" {
#endif

int abort_(void);
double c_abs(complex *);
void c_cos(complex *, complex *);
void c_div(complex *, complex *, complex *);
void c_exp(complex *, complex *);
void c_log(complex *, complex *);
void c_sin(complex *, complex *);
void c_sqrt(complex *, complex *);
double d_abs(double *);
double d_acos(double *);
double d_asin(double *);
double d_atan(double *);
double d_atn2(double *, double *);
void d_cnjg(doublecomplex *, doublecomplex *);
double d_cos(double *);
double d_cosh(double *);
double d_dim(double *, double *);
double d_exp(double *);
double d_imag(doublecomplex *);
double d_int(double *);
double d_lg10(double *);
double d_log(double *);
double d_mod(double *, double *);
double d_nint(double *);
double d_prod(float *, float *);
double d_sign(double *, double *);
double d_sin(double *);
double d_sinh(double *);
double d_sqrt(double *);
double d_tan(double *);
double d_tanh(double *);
double derf_(double *);
double derfc_(double *);
integer do_fio(ftnint *, char *, ftnlen);
integer do_lio(ftnint *, ftnint *, char *, ftnlen);
integer do_uio(ftnint *, char *, ftnlen);
integer e_rdfe(void);
integer e_rdue(void);
integer e_rsfe(void);
integer e_rsfi(void);
integer e_rsle(void);
integer e_rsli(void);
integer e_rsue(void);
integer e_wdfe(void);
integer e_wdue(void);
integer e_wsfe(void);
integer e_wsfi(void);
integer e_wsle(void);
integer e_wsli(void);
integer e_wsue(void);
int ef1asc_(ftnint *, ftnlen *, ftnint *, ftnlen *);
integer ef1cmc_(ftnint *, ftnlen *, ftnint *, ftnlen *);
double erf(double);
double erf_(float *);
double erfc(double);
double erfc_(float *);
integer f_back(alist *);
integer f_clos(cllist *);
integer f_end(alist *);
void f_exit(void);
integer f_inqu(inlist *);
integer f_open(olist *);
integer f_rew(alist *);
int flush_(void);
void getarg_(integer *, char *, ftnlen);
void getenv_(char *, char *, ftnlen, ftnlen);
short h_abs(short *);
short h_dim(short *, short *);
short h_dnnt(double *);
short h_indx(char *, char *, ftnlen, ftnlen);
short h_len(char *, ftnlen);
short h_mod(short *, short *);
short h_nint(float *);
short h_sign(short *, short *);
short hl_ge(char *, char *, ftnlen, ftnlen);
short hl_gt(char *, char *, ftnlen, ftnlen);
short hl_le(char *, char *, ftnlen, ftnlen);
short hl_lt(char *, char *, ftnlen, ftnlen);
integer i_abs(integer *);
integer i_dim(integer *, integer *);
integer i_dnnt(double *);
integer i_indx(char *, char *, ftnlen, ftnlen);
integer i_len(char *, ftnlen);
integer i_mod(integer *, integer *);
integer i_nint(float *);
integer i_sign(integer *, integer *);
integer iargc_(void);
ftnlen l_ge(char *, char *, ftnlen, ftnlen);
ftnlen l_gt(char *, char *, ftnlen, ftnlen);
ftnlen l_le(char *, char *, ftnlen, ftnlen);
ftnlen l_lt(char *, char *, ftnlen, ftnlen);
void pow_ci(complex *, complex *, integer *);
double pow_dd(double *, double *);
double pow_di(double *, integer *);
short pow_hh(short *, shortint *);
integer pow_ii(integer *, integer *);
double pow_ri(float *, integer *);
void pow_zi(doublecomplex *, doublecomplex *, integer *);
void pow_zz(doublecomplex *, doublecomplex *, doublecomplex *);
double r_abs(float *);
double r_acos(float *);
double r_asin(float *);
double r_atan(float *);
double r_atn2(float *, float *);
void r_cnjg(complex *, complex *);
double r_cos(float *);
double r_cosh(float *);
double r_dim(float *, float *);
double r_exp(float *);
double r_imag(complex *);
double r_int(float *);
double r_lg10(float *);
double r_log(float *);
double r_mod(float *, float *);
double r_nint(float *);
double r_sign(float *, float *);
double r_sin(float *);
double r_sinh(float *);
double r_sqrt(float *);
double r_tan(float *);
double r_tanh(float *);
void s_cat(char *, char **, integer *, integer *, ftnlen);
integer s_cmp(char *, char *, ftnlen, ftnlen);
void s_copy(char *, char *, ftnlen, ftnlen);
int s_paus(char *, ftnlen);
integer s_rdfe(cilist *);
integer s_rdue(cilist *);
integer s_rnge(char *, integer, char *, integer);
integer s_rsfe(cilist *);
integer s_rsfi(icilist *);
integer s_rsle(cilist *);
integer s_rsli(icilist *);
integer s_rsne(cilist *);
integer s_rsni(icilist *);
integer s_rsue(cilist *);
int s_stop(char *, ftnlen);
integer s_wdfe(cilist *);
integer s_wdue(cilist *);
integer s_wsfe(cilist *);
integer s_wsfi(icilist *);
integer s_wsle(cilist *);
integer s_wsli(icilist *);
integer s_wsne(cilist *);
integer s_wsni(icilist *);
integer s_wsue(cilist *);
void sig_die(const char *, int);
integer signal_(integer *, void (*)(int));
integer system_(char *, ftnlen);
double z_abs(doublecomplex *);
void z_cos(doublecomplex *, doublecomplex *);
void z_div(doublecomplex *, doublecomplex *, doublecomplex *);
void z_exp(doublecomplex *, doublecomplex *);
void z_log(doublecomplex *, doublecomplex *);
void z_sin(doublecomplex *, doublecomplex *);
void z_sqrt(doublecomplex *, doublecomplex *);
doublereal etime_(float *tarray);

#ifdef __cplusplus
	}
#endif
